version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/myLabeller/public/:/usr/src/app'
      - './docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/myLabeller/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: pma
    restart: always
    environment:
      - PMA_HOST=mysql
    ports:
      - 81:80
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  data-volume: {}